### ISSUE TITLE
Lack of kerning in math font

### ISSUE THREAD

**Issue by netheril96** [khaledhosny/xits#25]
XITS Math lacks kerning, which means the spacing between letters do not seem uniform. A simple $ABCDEFGabcdefg$ with `unicode-math` will reveal the problem.

<hr/>

Currently one can use this temporary fix: instead of a single line

```
\setmathfont{XITS Math}
```

we can use three lines

```
\setmathfont{XITS Math}
\setmathfont[range={\mathit}]{XITS Italic}
\setmathfont[range={\mathrm}]{XITS}
```

**Comment by p-bro** [comment]
If I do this, I lose all $\partial$ symbols, they're not printed any more.

**Comment by khaledhosny** [comment]
The lack of kerning is the norm in OpenType fonts now and support for kerning is inconsistent nor non-existent in math layout engine, and I don’t think this is going to change.
