### ISSUE TITLE
new language (n'ko) support

### ISSUE THREAD

**Issue by ckairaba** [khaledhosny/xits#29]
Is it possible to add N'ko language support in xits-math ?
In n'ko, we use the mirrored version of math symbols because N'ko is a RTL alphabet like arabic.
Here are some links :
en.wikipedia.org/wiki/N%27Ko_alphabet
http://www.kanjamadi.com/
http://www.unicode.org/charts/PDF/U07C0.pdf

**Comment by khaledhosny** [comment]
I don’t think I’m going to do this, sorry. Patches are welcome, though.
