### ISSUE TITLE
Implement third form of Integral symbol

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [khaledhosny/xits#59]
In [Wikipedia](https://en.wikipedia.org/wiki/Integral_symbol) I found another form of Integral symbol which leans to the left. I suggest adding a style set to make it available.

**Comment by KrasnayaPloshchad** [comment]
https://github.com/stipub/stixfonts/issues/105

**Comment by khaledhosny** [comment]
I don’t think anyone is missing it.
